<?php
require_once("../_class.dba.inc.php");
require_once("../_conf.dba.inc.php");
require_once("../_static.session.inc.php");
validate_session();
?>
<html>
<head>
<title>Privacy Policy</title>
<link rel="stylesheet" type="text/css" media="screen" href="../style.css" />
<?php include('../header.php');?>

</head>
<body class="tos">
<?php include('../sidebar.php');?>
<div id="main-container"><div id="main">
<h1>Privacy Policy</h1>

<p class="has-line-data" data-line-start="2" data-line-end="3">Our company StockKnowledge Corp. (or commercially known as Stock Knowledge), made this Privacy Policy to describe our practices regarding the information we collect through our computer platforms and any other interactive features or services owned or controlled by Stock Knowledge that post a link to this Privacy Policy (each, a “Service” and collectively, the “Services”), as well as any information we collect offline and combine in our databases. Certain features discussed in this Privacy Policy may not be offered on each Service at any particular time. Note that we combine the information we collect from you through all of our web sites, mobile applications, and other Services.</p>
<p class="has-line-data" data-line-start="4" data-line-end="5">Note about Children: Our Services are general-audience in nature, and children below 16 years old must be supervised and facilitated by a guardian or any person having parental authority over such child.</p>
<p class="has-line-data" data-line-start="6" data-line-end="7">Please read this Privacy Policy to learn more about:</p>
<p class="has-line-data" data-line-start="8" data-line-end="12">SUMMARY<br>
WE FULLY DESCRIBE OUR PRIVACY PRACTICES BELOW IN THIS PRIVACY POLICY. THIS SUMMARY PROVIDES AN OVERVIEW OF SOME IMPORTANT INFORMATION REGARDING OUR USE AND SHARING OF YOUR INFORMATION, AND THIRD PARTIES WHO MAY SERVE ADVERTISEMENTS AND WHO MAY SET COOKIES OR WEB BEACONS OR SIMILAR TRACKING TECHNOLOGIES WHEN YOU USE THE SERVICES. PLEASE REVIEW OUR FULL PRIVACY POLICY BEFORE USING OUR SERVICES.<br>
We primarily use the information we collect when you use the Services in connection with your relationship with Stock Knowledge, your use of the Services, and for sending you information from us or on behalf of certain third parties. This includes linking you to other members of the Stock Knowledge community and, in some cases, may allow you to engage in real-time video- or text-based chat with another community member. It also includes providing offers to you based on information you provide or we collect, and your use of the Services. Please review the “INFORMATION COLLECTION ”and “HOW WE USE YOUR INFORMATION” sections of this Privacy Policy for a full description of the information we collect, including Personal Information (as defined below), and how we use that information. Remember that if you create a Profile (as defined below) or participate in community forums and similar features on the Services, your information may be public. Note that we do not share your Personal Information with third parties for their direct marketing purposes without your consent; however, we may share your Personal Information under certain limited circumstances. In addition, we may share hashed or otherwise de-identified information with third parties for our or their marketing purposes. For more details, please review the section below entitled “Information Sharing.”<br>
Stock Knowledge works with network advertisers, analytics service providers and other vendors to serve our and third party advertisements on and through the Services and elsewhere online; to provide us with information regarding traffic on the Services, including the pages viewed and the actions users take when visiting the Services; and to provide us with information regarding the use of the Services and the effectiveness of our advertisements. For example, if you click on a Stock Knowledge advertisement, our service provider(s) may be able to tell us the advertisement you clicked on and where you were viewing the advertisement. The advertisements you see may be served by one or more third parties, who may use information about your activities on the Services, and other web sites and services, to provide you targeted advertising based upon your interests. Our ad network providers, the advertisers, ad agencies, analytics service providers and other vendors may set and access their own tracking devices (including cookies and web beacons) and they may otherwise collect or have access to information about you and your visits to and activity on the Services, as well as on other web sites or online services. We may share non-Personal information, including hashed or de-identified information, with these parties. And some of these parties may collect Personal Information when you visit the Services or other web sites and services. Please review “THIRD PARTY AD NETWORKS AND ANALYTICS PROVIDERS” for additional information. Some of the companies who serve these targeted ads participate in a self-regulatory program that allows you to opt-out of having information about you used for this purpose, and you may access that opt-out by contacting us. Please note this does not opt you out of being served advertising. You will continue to receive generic ads while using the Services and elsewhere online.</p>
<p class="has-line-data" data-line-start="13" data-line-end="20">INFORMATION COLLECTION<br>
Registration and Other Information You Provide<br>
The Services may collect “Personal Information” (which is information that can be used to identify or contact a specific individual, such as your name and email address), account information (such as a password or other information that helps us confirm that it is you accessing your account) and demographic or other information (such as your school, gender, age or birthdate and zip code and information about your interests and preferences). We will also collect payment information (typically, credit card account information) if you choose to purchase products or services through the Services.<br>
Some Services may allow you to use the Service to offer your own products or services for sale such as when you register as a tutor. If you use the Services for such purposes or in any other manner that may necessitate payment from Stock Knowledge to you, we may collect additional information from you, such as your Social Security Number or taxpayer identification number, as necessary to facilitate payment and to comply with related legal obligations.<br>
Sensitive personal data revealing racial or ethnic origin, political opinions, religious or philosophical beliefs, or trade union membership, and the processing of genetic data, biometric data for the purpose of uniquely identifying you, data concerning your health or data concerning your sex life or sexual orientation, shall not be collected, except when consented to, carried out in the course of StockKnowledge’s legitimate activities with appropriate safeguards, necessary in the interest of the public, or for scientific, historical research or statistical purposes.<br>
Any sensitive personal information collected combined with Personal Information will be treated as Personal Information.<br>
Any information that we collect from you shall be processed lawfully, fairly and in a transparent manner. It shall only be collected for specified, explicit and legitimate purposes and shall not be further processed in a manner that is incompatible with those purposes. Collection shall be adequate, relevant and limited to what is necessary in relation to the purposes for which they are processed. Information collected shall be treated with integrity and confidentiality.</p>
<p class="has-line-data" data-line-start="21" data-line-end="28">Your Profile, Community Forums and User Content<br>
You may have the opportunity to create a profile, which consists of information about you, which may include Personal Information, photographs, information about your academic and work history, your interests and activities, your use of the Services and other information (“Profile”). Some of the information in your Profile may be visible to third parties or to everyone, depending on the nature of the information and the privacy settings you choose when you sign in to your account on the Service where you created your Profile. Your Profile may also be indexed by and displayed by internet search providers when someone searches for your name. Stock Knowledge does not control how frequently third-party search engines update their indexes; consequently, their information may be outdated and still available for a period of time even if you discontinue use of the Service.<br>
Note that in order to provide services and opportunities to you, educational organizations and other third parties may be able to review certain information in your Profile for some of the Services, whether or not you have limited public access to that information. You may have the opportunity to control whether this information is shared, but some information may be shared automatically — all as disclosed on the web site or other service where you created your Profile. Stock Knowledge does not share your contact information (email, full postal address or phone number) with those third parties unless you request or agree to that sharing. However, Stock Knowledge may send you information and offers from third parties and information about the Services, and you may not be able to opt-out from these messages without closing your account.<br>
The Services may provide you the opportunity to participate and post content publicly in forums, through interactive features and through other communication functionality (“Stock Knowledge Forums”). You may choose, through such features or otherwise, to submit or post content, such as reviews, problems, suggestions, ideas, solutions, questions, answers, class notes, course outlines, comments, testimonials, feedback, messages, images, videos, text or other material (“User Content”). Your User Content may also be posted in your Profile. Please think carefully about what you post and before including Personal Information in your User Content. You may edit or remove your Profile information, but you may not be able to remove answers or postings or other uploaded User Content on some Services. To request removal of content you posted publicly on the Services, contact us at <a href="mailto:legal@theknowledgetools.com"><span class="__cf_email__" data-cfemail="34585153555874405c515f5a5b435851505351405b5b58471a575b59">legal@theknowledgetools.com</span></a>. We will honor removal requests received from registered users. Other removal requests received, may, in our sole discretion, be honored or refused. In some cases, we may remove only your Personal Information but maintain the rest of your User Content. Note that removal of public postings does not ensure complete or comprehensive removal of the content or information posted.<br>
Note that anything you post to a Community Forum may be public. If you choose to voluntarily disclose Personal Information and any sensitive personal information in your Profile or a Community Forum, that information will be considered public information and shall constitute as a waiver of the protections provided for under this Privacy Policy.<br>
In addition, the Services may allow members to communicate and collaborate with each other, including some Services that allow members to engage in one-on-one communication using a text chat feature. If you create an account, participate in a Community Forum or choose to communicate with others through the Services, certain information about you may be disclosed in connection with your or others’ use of the Services, including certain information about you and your network (such as your name and profile photo, the number of your connections, and the names and pictures of your connections). Our servers may record and we may retain records of the content of any such user-to-user communications.<br>
We allow other users to use contact information they have about you, such as your email address, to find you, including through contact importers and search, and they may also contact you through the Services.</p>
<p class="has-line-data" data-line-start="29" data-line-end="42">Third Party Services, Social Media Platforms, and Information Third Parties Provide About You<br>
Third parties may provide us with information about you. For example, if you are on a third party web site, and you opt-in to receive information from us, that third party will forward information about you to us so that we may contact you as requested.<br>
We also may supplement the information we collect with outside records from third parties in order to provide you with information, services or goods you have requested, to enhance our ability to serve you, to tailor our content to you and to offer you opportunities to purchase products or services that we believe may be of interest to you. We may combine the information we receive from those other sources with information we collect through the Services. In those cases, we will apply this Privacy Policy to the combined information.<br>
The Services may permit interactions between the Services and a third party web site or service, such as enabling you to “like” a product within our Services or “share” content to other web sites. If you choose to “like” or “share” content or to otherwise post information from or via the Services to a third party web site, feature or application, that information may be publicly displayed, and the third party web site may have access to information about you and your use of our Services. Similarly, if you post information on a third party platform that references Stock Knowledge or one of the Services, your post may be published on our Services in accordance with terms of that third party. These features may collect your IP address or other Device Identifier, which page you are visiting on our web site, and may set a cookie to enable the third party feature to function properly. Third party features and applications are either hosted by a third party or hosted directly on our Services. Your interactions with these features are governed by the privacy policy of the company providing it.<br>
You may also choose to participate in a third party application or feature through our Services (such as linking the Services with another web site or interactive service) or on a third party web site or service (such as one of our Facebook applications or a similar application or feature on a third party web site or service) through which you allow us to collect (or the third party to share) information about you, including Personal Information. Information about you, including your name and profile photo, may be shown to other users of the Services if you are logged in through the Services or through a third party web site or service. The third party may allow you to remove the application or feature, in which case we will no longer collect information about you through the application or feature, but we may retain the information previously collected. When you choose to participate, you may be opting to link your activity on our Services with that third party web site or service, which may then collect information about your visits to our Services and may publish that activity as you request to your profile or similar feature with that third party (such as if you choose to share a purchase you made on <a href="http://theknowledgetools.com">theknowledgetools.com</a> with your connections on the third party web site). In some instances, we may require that you participate in the Services through a third party application or feature and, if you choose not to authorize or use the required third party application or feature, you will not be able to use the applicable Service.<br>
The information we collect is subject to this Privacy Policy. The information collected and stored by the third party remains subject to the third party’s privacy practices, including whether the third party continues to share information with us, the types of information shared, and your choices with regard to what is visible to others on that third party web site and service. The third party may allow you to remove the application or feature, in which case we will no longer collect information about you through the application or feature, but we may retain the information previously collected.<br>
Referral Features<br>
The Services may offer referral features whereby users may use an email tool to invite friends to use the Services using a one-time email. Stock Knowledge stores this information for the purpose of verification, as well as tracking the success of our referral program. Stock Knowledge will not use those referred email addresses for any other purpose (unless, of course, the referred user comes to a Service and registers as a user, in which case Stock Knowledge may use the email address provided by the referred user in accordance with this Privacy Policy). The referred person may contact us at <a href="mailto:legal@theknowledgetools.com" class="__cf_email__" data-cfemail="335f5654525f73475b56585d5c445f56575456475c5c5f401d505c5e475c">legal@theknowledgetools.com</a> request that we remove this information from our active database.<br>
Information Stock Knowledge Collects Automatically When You Access The Services<br>
Like other web sites and online services, we and our third party service providers may automatically collect certain “Usage Information” whenever you access and use the Services, including browsing content on a Stock Knowledge Service or clicking on a Stock Knowledge advertisement.<br>
Usage Information may include the browser and operating system you are using, the URL or advertisement that referred you to our Services (if applicable), the search terms you entered into a search engine that lead you to our Services (if applicable), all of the areas within our Services that you visit (including information about products you use, how you use certain services, the time you spend on each page or using each service, and any ads you may view), and the time of day you used the Services. Usage Information also includes information collected from interactive services (including our ereader), such as notes you take and engagement during study sessions, among other information.<br>
We may use Usage Information for a variety of purposes, including to tell you about people or events nearby, to provide special offers, to serve advertisements, to select appropriate content to display to you, and to enhance or otherwise improve the Services and our products.<br>
In addition, we automatically collect your IP address or other unique identifier (“Device Identifier”) for any computer, mobile phone or other device (any, a “Device”) you may use to access the Services. A Device Identifier is a number that is automatically assigned to your Device used to access a Service, and our servers identify your Device by its Device Identifier. Some mobile service providers may also provide us or our third party service providers with information regarding the physical location of the Device used to access a Service. Usage Information is generally non-identifying, but if we associate it with you as a specific and identifiable person, we treat it as Personal Information.</p>
<p class="has-line-data" data-line-start="43" data-line-end="51">Usage Information is collected via tracking technologies, including:<br>
Cookies and Log Files:Stock Knowledge uses cookies, log files or similar technologies to track usage of our Services. A cookie is a data file that resides on your computer, and which allows Stock Knowlegde to recognize you when you return using the same computer and web browser. If your browser settings do not allow cookies, you will not be able to use our Services as fully as intended. Log files are the record of your visits to the Services and include Usage Information. Like the information you enter at registration or in your Profile, cookie and log file data is used to customize your experience when you use the Services. Third parties may also set cookies as you interact with the Service. Third parties may use session IDs and cookies to make it easier for you to use our Services and place orders, to deliver online advertising, and for other purposes.<br>
One type of cookie we use, known as a “persistent” cookie, is set once you’ve logged in to your account on the Services. If you do not log out of your account, then the next time you visit, the persistent cookie will allow us to recognize you as an existing user so you will not need to log in before using the Services. If you are using a public computer or sharing your private computer with others, you should log out of your account after each visit. If you log out of a Service, you will need to re-enter your password the next time you visit in order to log in to your account. You can remove persistent cookies by following directions provided in your Internet browser’s “help” file. We also use a cookie which functions as a “session” cookie, meaning that it is used to identify a particular visit. Session cookies expire after a short time or when you close your web browser.<br>
Web Beacons:We, as well as our affiliate program partners, service providers, and other third parties, may employ a software technology called web beacons (a.k.a. clear gifs), that help us better manage content on our Services by informing us of what content is effective. Clear gifs are tiny graphics with a unique identifier, similar in function to cookies, and are used to track the online movements of web users for our affiliate program. In contrast to cookies, which are stored on a user’s computer hard drive, clear gifs are embedded invisibly on web pages. This information is used to help improve the overall quality and experience of our Services. We tie the information gathered by clear gifs to our customers’ Personal Information.<br>
An Embedded Script:is programming code that is designed to collect information about your interactions with the Services, such as the links you click on. The code is temporarily downloaded onto your computer or other device from our server or a third party service provider and is deactivated or deleted when you disconnect from the Services.<br>
Flash &amp; HTML5: We use Local Storage Objects (LSOs) such as HTML5 to store content, information and preferences. Third parties with whom we partner to provide certain features on our site or to display advertising based upon your Web browsing activity use LSOs such as HTML 5 &amp; Flash to collect and store information. Various browsers may offer their own management tools for removing HTML5 LSOs. To manage Flash LSOs please click here:<br>
<a href="https://www.macromedia.com/support/documentation/en/flashplayer/help/settings_manager07.html">http://www.macromedia.com/support/documentation/en/flashplayer/help/settings_manager07.html</a><br>
In addition, we may use a variety of other technologies that collect similar information for security and fraud detection purposes.</p>
<p class="has-line-data" data-line-start="52" data-line-end="54">INFORMATION SHARING<br>
Stock Knowledge does not share your Personal Information with third parties for their marketing purposes without your consent. Stock Knowledge may share non-Personal Information, such as aggregate user statistics, de-identified information, demographic information, and Usage Information with third parties, including advertisers, content providers, and analytics providers; and third parties may collect non-Personal Information when you visit the Services. Demographic information may include information related to your gender, age, graduation years, as well as other scholastic-related information. We may create de-identified information by removing all information that can be used to directly identify or contact you as a specific individual, such as your name and email address. We also may share your Personal Information with third parties with your consent, as disclosed at the time you provide us with information, and as described below or otherwise in this Privacy Policy.</p>
<p class="has-line-data" data-line-start="55" data-line-end="59">When You Request That We Share Your Information: We may offer opportunities and features through the Services that are brought to you by a third party or that otherwise involve sharing your information with a third party. If you request or agree at that time to have your information shared, your information will be disclosed to that third party (or parties) and will be subject to the privacy policy and practices of that third party. This includes, without limitation, instances in which you use our Services to purchase products or services provided, in whole or part, by third parties. You also may request, sometimes through your use of an interactive feature or social media feature, that we share information about you with a third party or publicly, and we will typically do so under those circumstances.<br>
Service Providers: We will share your Personal Information with third parties to provide services to us or you in connection with the Services, but subject to confidentiality obligations, which limit their use and disclosure of such information. For example, we may provide your Personal Information to companies that provide services to help us with our business activities, such as shipping your order, sending our emails, or offering customer service. If you purchase any products or services, our billing partner will receive billing and financial information (e.g., credit card numbers) necessary to process your charges, including your postal and e-mail addresses, depending on your payment method.<br>
Administrative, Legal Reasons &amp; Academic Integrity Investigations: We may also disclose your information, including Personal Information, in response to a subpoena or when required by law; in response to bankruptcy proceedings; to defend our rights; in response to a written request from law enforcement regarding an investigation into criminal activity that may have occurred through or in any way using Stock Knowledge’s Services or property; to provide information to a claimed owner of intellectual property who claims that content you have provided to us infringes on their rights; upon request of an academic institution connected to an investigation into academic integrity; to protect and/or defend any applicable Terms of Use or other policies applicable to the Services; or to protect the personal safety, rights, property or security of any organization or individual. We may also use Device Identifiers, including IP addresses, to identify users, and may do so in cooperation with copyright owners, Internet service providers, wireless service providers or law enforcement agencies in our discretion. These disclosures may be carried out without notice to you.<br>
Business Transitions: Stock Knowledge may share Personal Information with its parent, subsidiaries and affiliates, primarily for business and operational purposes. In the event that Stock Knowledge goes through a business transition, such as a merger, acquisition by another company, or sale of all or a portion of its assets, bankruptcy, or other corporate change, including, without limitation, during the course of any due diligence process, your information, including Personal Information, will likely be among the assets transferred. You will be notified via email and/or a prominent notice on Services of any change in ownership or uses of your Personal Information, as well as any choices you may have regarding your Personal Information. This Privacy Policy will become binding upon the new owner of the information until amended.</p>
<p class="has-line-data" data-line-start="60" data-line-end="61">However, any transfer of personal information to a third country or to an international organization shall take place only upon compliance with the conditions under the General Data Protection Regulation, including for onward transfers of personal data from the third country or an international organization to another third country or to another international organization.</p>
<p class="has-line-data" data-line-start="62" data-line-end="63">Sweepstakes, Contests and Promotions: We may offer sweepstakes, contests, and other promotions (“Promotion”) that may require registration. By participating in a Promotion, you are agreeing to governing terms, conditions or official rules, which may contain specific requirements of you, including allowing the sponsor(s) of the Promotion to use your name, voice, likeness or other indicia of persona in advertising or marketing associated with the Promotion. If you choose to enter a Promotion, Personal Information, such as your name and shipping address, may be disclosed to third parties or the public in connection with the administration of such Promotion, including, without limitation, in connection with winner selection, prize fulfillment, and as required by law or permitted by the Promotion’s official rules, such as on a winners list.</p>
<p class="has-line-data" data-line-start="64" data-line-end="65">How We Respond To Do Not Track Signals:</p>
<p class="has-line-data" data-line-start="66" data-line-end="67">Please note that your browser setting may allow you to automatically transmit a “Do Not Track” signal to web sites and online service you visit. There is no consensus among industry participants as to what “Do Not Track” means in this context. Like many web sites and online services, Stock Knowledge does not alter its practices when it receives a “Do Not Track” signal from a visitor’s browser. To find out more about “Do Not Track”, please visit <a href="http://www.allaboutdnt.com">http://www.allaboutdnt.com</a>.</p>
<p class="has-line-data" data-line-start="68" data-line-end="69">HOW WE USE YOUR INFORMATION</p>
<p class="has-line-data" data-line-start="70" data-line-end="71">We use information about you, including Personal Information, the information you provide in your Profile, User Content, and Usage Information to: (1) process a transaction you initiate, allow you to participate in features we offer and provide customer service, such as responding to questions, complaints or comments; (2) tailor content, recommendations, information and offers we display to you, both on the Services and elsewhere online (this includes sending or displaying special offers or advertisements from us or third-parties); (3) email or otherwise provide you with information, products, services, or suggestions; (4) process your registration with our Services, including verifying your e-mail address is active and valid; (5) improve the Services and our products, and for internal business purposes, including the measurement of ad effectiveness; (6) contact you with regard to your use of the Services and, in our discretion, changes to our policies; and (7) permit other Stock Knowledge users to contact you, and vice versa; (8) to provide you with location features and services (e.g., telling you about local deals and events); (9) to assess your employment application for a position with Stock Knowledge (or an entity related to Stock Knowledge) and prepare related governmental and internal statistics reports; and (10) as described in the Privacy Policy and for purposes disclosed at the time you provide your information or otherwise with your consent. We may also use non-personal information, including information that has been de-identified (typically by using a mathematical process known as a “hash”), to make inferences about you and offers and content you may be interested in, to serve you with relevant advertising, and to allow others to do so.</p>
<p class="has-line-data" data-line-start="72" data-line-end="73">Please note that information submitted on the Services via a “Contact Us” or other similar function may not receive a response. We will not use the information provided via these functions to contact you for marketing purposes unrelated to your request unless you agree otherwise.</p>
<p class="has-line-data" data-line-start="76" data-line-end="77">THIRD PARTY AD NETWORKS AND ANALYTICS PROVIDERS</p>
<p class="has-line-data" data-line-start="78" data-line-end="79">Stock Knowledge works with network advertisers, ad agencies, analytics service providers and other vendors for advertising and analytics services, including to serve our and third party advertisements on and through the Services and elsewhere online; to provide us with information regarding traffic on the Services, including the pages viewed and the actions users take when visiting the Services; and to provide us with information regarding the use of the Services and the effectiveness of our advertisements. For example, if you click on a Stock Knowledge advertisement, our service provider(s) may be able to tell us the advertisement you clicked on and where you were viewing the advertisement; likewise, if you click on an ad you see on our Services, our service provider(s) may be able to tell which page you were visiting on our Services and pass that information to the advertiser. The advertisements you see may be served by one or more third parties, who may use information collected over time about your activities on the Services, and other web sites and services, to provide you targeted advertising based upon your interests.</p>
<p class="has-line-data" data-line-start="80" data-line-end="81">Stock Knowledge may share non-Personal Information, such as de-identified (including hashed) information, location information, demographic information, and Usage Information with these third parties. Third party advertising and analytics providers may collect similar information through the Services, they may set and access their own tracking devices (including cookies and web beacons) and they may otherwise collect or have access to information about you and your online browsing activities. Some of these third parties may collect Personal Information over time when you visit the Services or other web sites and services.</p>
<p class="has-line-data" data-line-start="82" data-line-end="83">Some of the companies who serve these targeted ads participate in a self-regulatory program that allows you to opt-out of having information about you used for this purpose, and you may access that opt-out by clicking here. Alternatively, you may opt-out of targeted ads by visiting the Digital Advertising Alliance Consumer Choice page at <a href="http://www.aboutads.info/choices/">http://www.aboutads.info/choices/</a> or the Network Advertising Initiative consumer opt-out page at <a href="https://www.networkadvertising.org/managing/opt_out.asp">http://www.networkadvertising.org/managing/opt_out.asp</a>. Please note this does not opt you out of being served advertising. You will continue to receive generic ads while using the Services and elsewhere online.</p>
<p class="has-line-data" data-line-start="84" data-line-end="85">MOBILE USE</p>
<p class="has-line-data" data-line-start="86" data-line-end="87">If you use the Services through a mobile device or one of our mobile applications, we will collect Usage Data, which may include your mobile carrier. If you have opted-in to share your precise location with us through one of our mobile applications, you can turn off the collection of precise location information through your Device settings. We may still be able to infer your approximate location through other information we collect, such as IP address. You agree that Stock Knowledge may store and use that information for security purposes (for example, for user verification and to ensure that Stock Knowledge’s APIs are being used appropriately). You also acknowledge and agree that use of the Services through a mobile device may cause data to be displayed on and through your mobile device which may be viewed by your mobile carrier or other access provider.</p>
<p class="has-line-data" data-line-start="88" data-line-end="89">We use mobile analytics software to allow us to better understand the functionality of our Mobile Software on your phone. This software may record information such as how often you use the application, the events that occur within the application, aggregated usage, performance data, and where the application was downloaded from. We do not link the information we store within the analytics software to any personally identifiable information you submit within the mobile application.</p>
<p class="has-line-data" data-line-start="90" data-line-end="91">Text messages: You may be able to opt-in to receiving text messages from Stock Knowledge. You may opt-out by replying “STOP” to one of the text messages received.</p>
<p class="has-line-data" data-line-start="92" data-line-end="93">Push Notification: We will send you push notifications if you agree to receive them to announce special deals and to send you your itinerary. You may opt-out of receiving these at any time by going to the phone settings and turning them off.</p>
<p class="has-line-data" data-line-start="94" data-line-end="95">UPDATING YOUR ACCOUNT INFORMATION AND CONTROL OVER STOCK KNOWLEDGE EMAILS</p>
<p class="has-line-data" data-line-start="96" data-line-end="97">You may be able to review the information you provided to us on a Service and make any desired changes, or to the settings for your account on that Service, by logging in to your account for that Service and rectifying or restricting the information. Any rectification or erasure of personal information or restriction of processing carried out shall be disclosed to each recipient to whom your personal information have been disclosed, unless this proves impossible or involves disproportionate effort.</p>
<p class="has-line-data" data-line-start="98" data-line-end="99">You also may be able to limit the information you receive from us by adjusting your settings. All changes to your email settings and preferences must be made in your account preferences page on the applicable Service or, for email, by using the unsubscribe button at the bottom of the Stock Knowledge email. However, we reserve the right to send you information on our behalf and on behalf of third parties through the Services. If you no longer want to receive information from us, you will need to close your account for that Service.</p>
<p class="has-line-data" data-line-start="100" data-line-end="102">CLOSING YOUR ACCOUNT<br>
If you wish to close your account with one of our Services, please send your request to <a href="mailto:legal@theknowledgetools.com"><span class="__cf_email__" data-cfemail="42313732322d303602362a27292c2d352e27262527362d2d2e316c212d2f">legal@theknowledgetools.com</span></a> and we will remove your Personal Information and Profile, if applicable, from the active databases for the Service(s) you request. Please let us know which Service(s) you wish to close and send your request using an email account that you have registered with Stock Knowledge under your name. You typically will receive a response to a request sent to <a href="mailto:legal@theknowledgetools.com"><span class="__cf_email__" data-cfemail="4d3e383d3d223f390d3925282623223a2128292a28392222213e632e2220">legal@theknowledgetools.com</span></a> within five business days of our receiving it. Requests to change your email preferences or unsubscribe from all emails may not be made through this email address, but rather must be submitted through one of the channels set out in the previous section.</p>
<p class="has-line-data" data-line-start="103" data-line-end="104">Even if your account is closed, information may remain in backup records and we may retain certain data for longer periods insofar as the personal information will be processed solely for archiving purposes in the public interest, scientific or historical research purposes or statistical purposes subject to implementation of the appropriate technical and organizational measures in order to safeguard the rights and freedoms of the data subject. Contents posted on or through the Services, such as in Community Forums, however, may not be deleted.</p>
<p class="has-line-data" data-line-start="105" data-line-end="106">THIRD PARTY CONTENT, LINKS TO OTHER SITES</p>
<p class="has-line-data" data-line-start="107" data-line-end="108">Certain content provided through the Services may be hosted and served by third parties, which may include third party widgets (such as those that allow you to “like” or “share” content with third party web sites and online services). In addition, the Services may link to third party web sites or content over which Stock Knowledge has no control and which are governed by the privacy policies and business practices of those third parties. In addition, third-party partners of Stock Knowledge from whom your order through the Services may have different privacy policies which apply to such partner’s use of your information. These third parties may independently collect data. Stock Knowledge is not responsible for the privacy practices or business practices of any third party.</p>
<p class="has-line-data" data-line-start="109" data-line-end="110">TESTIMONIALS</p>
<p class="has-line-data" data-line-start="111" data-line-end="112">We display personal testimonials of satisfied customers on our Services in addition to other endorsements. With your consent we may post your testimonial along with your name. If you wish to update or delete your testimonial, you can contact us at <a href="mailto:legal@theknowledgetools.com"><span class="__cf_email__" data-cfemail="c7aba2a0a6ab87b3afa2aca9a8b0aba2a3a0a2b3a8a8abb4e9a4a8aa">legal@theknowledgetools.com</span></a>.</p>
<p class="has-line-data" data-line-start="114" data-line-end="115">SECURITY</p>
<p class="has-line-data" data-line-start="116" data-line-end="117">Stock Knowledge takes commercially reasonable security measures to protect the Personal Information submitted to us, both during transmission and once we receive it. For example, when you enter sensitive information such as a credit card number and CCV2 number on our checkout forms, that information is encrypted to help protect the communications between you and our payment partners.</p>
<p class="has-line-data" data-line-start="118" data-line-end="119">However, no method of transmission over the Internet, or method of electronic storage, is 100% secure. Therefore, while we strive to use commercially acceptable means to protect your Personal Information, as in any real-life scenario, we cannot guarantee its absolute security. If you have any questions about security on our Services, you can email us at <a href="mailto:legal@theknowledgetools.com"><span class="__cf_email__" data-cfemail="5b373e3c3a371b2f333e3035342c373e3f3c3e2f3434372875383436">legal@theknowledgetools.com</span></a>.</p>
<p class="has-line-data" data-line-start="120" data-line-end="121">CONSENT TO TRANSFER</p>
<p class="has-line-data" data-line-start="122" data-line-end="123">The Services are operated in the Philippines. If you are located outside of the Philippines, please be aware that information we collect will be transferred to and processed in the Philippines. By using the Services, or providing us with any information, you fully understand and unambiguously consent to this transfer, processing and storage of your information in the Philippines in accordance with the Philippines’ Data Privacy Act of 2012 and its Implementing Rules and Regulations. Nonetheless, the technical and organizational measures set forth in this Privacy Policy strictly adheres to the General Data Protection Regulation of the European Commission.</p>
<p class="has-line-data" data-line-start="124" data-line-end="125">CHANGES TO THIS PRIVACY POLICY</p>
<p class="has-line-data" data-line-start="126" data-line-end="127">Stock Knowledge may update this Privacy Policy at any time and any changes will be effective upon posting of the revised Privacy Policy unless otherwise specified. In the event that there are material changes to the way we treat your Personal Information, we will display a notice through the Services of the updated Privacy Policy. We may also notify you in other ways in our discretion, such as through contact information you have provided. Your continued use of any of the Services after the effective date of the revised Privacy Policy will constitute your consent to the new Privacy Policy. However, we will not make material changes to how we treat previously collected Personal Information without first giving you the chance to consent (opt-in or opt-out). Note, however, that you may need to consent to our new Privacy Policy in order to continue to use the Services.</p>
<p class="has-line-data" data-line-start="128" data-line-end="129">QUESTIONS OR COMMENTS</p>
<p class="has-line-data" data-line-start="130" data-line-end="131">If you have questions or comments about this privacy policy, please email us at <a href="mailto:legal@theknowledgetools.com"><span class="__cf_email__" data-cfemail="c0aca5a7a1ac80b4a8a5abaeafb7aca5a4a7a5b4afafacb3eea3afad">legal@theknowledgetools.com</span></a></p>





</div></div>
<?php include('../footer.php');?>

</body>
</html> 
