<?php
require_once("../_class.dba.inc.php");
require_once("../_conf.dba.inc.php");
require_once("../_static.session.inc.php");
validate_session();
?>
<html>
<head>
<title>Terms of Use</title>
<link rel="stylesheet" type="text/css" media="screen" href="../style.css" />
<?php include('../header.php');?>

</head>
<body class="tos">
<?php include('../sidebar.php');?>
<div id="main-container"><div id="main">
<h1>Terms of Use</h1>

<p class="has-line-data" data-line-start="0" data-line-end="1">Welcome to Stock Knowledge!</p>
<p class="has-line-data" data-line-start="2" data-line-end="3">IMPORTANT! PLEASE CAREFULLY READ THESE TERMS OF USE, AS THEY AFFECT YOUR LEGAL RIGHTS AND OBLIGATIONS. The Stock Knowledge Terms of Use (“Terms of Use”) apply to the web and mobile applications and other interactive features or services that post a link to these Terms of Use (each, a “Service” and collectively, the “Services” or “Stock Knowledge Websites”). StockKnowledge, Corp. and our subsidiaries are referred to collectively in these Terms of Use as “Stock Knowledge,” “Stock Knowledge Websites,” “we” or “our.” “You,” “your” and “user” refer to any person or entity using the Services.</p>
<p class="has-line-data" data-line-start="4" data-line-end="5">These Terms of Use govern your use of the Services, regardless of how you access them, whether by computer, mobile device, or otherwise; and whether directly through our Services, or through any third-party website that links to them (“Linked Services“), and regardless of whether you are a registered user or a guest. By using the Services, you agree to the Terms of Use. If you do not agree to the Terms of Use, you are not authorized to use the Services and you must cease all such use immediately.</p>
<p class="has-line-data" data-line-start="6" data-line-end="7">ARBITRATION NOTICE: UNLESS YOU OPT OUT OF ARBITRATION WITHIN 30 DAYS OF THE DATE YOU FIRST AGREE TO THESE TERMS OF USE BY FOLLOWING THE OPT-OUT PROCEDURE SPECIFIED IN THE “ARBITRATION” SECTION BELOW, AND EXCEPT FOR CERTAIN TYPES OF DISPUTES DESCRIBED IN THE “ARBITRATION” SECTION BELOW, YOU AGREE THAT DISPUTES BETWEEN YOU AND STOCK KNOWLEDGE WILL BE RESOLVED BY BINDING, INDIVIDUAL ARBITRATION AND YOU WAIVE YOUR RIGHT TO PARTICIPATE IN A CLASS ACTION LAWSUIT OR CLASS-WIDE ARBITRATION.</p>
<p class="has-line-data" data-line-start="8" data-line-end="9">In some instances, both these Terms of Use and a separate document that provides additional conditions may apply to a service or product offered via the Services (“Additional Terms“). To the extent there is a conflict between these Terms of Use and any Additional Terms, the Additional Terms will control unless the Additional Terms expressly state otherwise.</p>
<p class="has-line-data" data-line-start="10" data-line-end="12">CONTENTS<br>
Account Registration &amp; Termination</p>
<p class="has-line-data" data-line-start="13" data-line-end="14">You may only have one Stock Knowledge account for use of the Services. You may not create or use more than one account, and you may not share your account or any of the Services with others. All information you provide to create an account must be accurate and complete. You may not impersonate any other person or use a name that is not your own. It is your responsibility to update your account information to keep it current and accurate. When you set up an account, you must also choose a password. You are solely responsible for maintaining the confidentiality of your password, and for any and all use of your account. You agree not to use the account, username, or password of another user at any time, nor to disclose your password to any third party. You agree you will not sell or share or otherwise transfer your membership or any membership rights. You agree to notify Stock Knowledge immediately if you suspect any unauthorized use of your account or access to your password. Stock Knowledge has the right to terminate your account for any reason at our sole discretion without notice to you.</p>
<p class="has-line-data" data-line-start="15" data-line-end="17">Age and Residence Requirements;<br>
The Services are available to individuals age 10 and over; note, however, ages below 13 16 years old users must be supervised and facilitated by a guardian or a person exercising parental authority over such child. You may register for an account regardless of where you live. Our textbook rentals and sales are only available to residents of the Philippines. All financial transactions will be processed in Philippine peso. The Services are not intended for distribution or use in any jurisdiction or country where such distribution or use would be contrary to law or regulation or which would subject Stock Knowledge to any registration requirement within such jurisdiction or country. By registering, you certify that you are not on any list of restricted persons with whom it is unlawful for a Philippines company to do business. Stock Knowledge operates the majority of its Services in the Philippines. Stock Knowledge makes no representations or warranties that the Services are appropriate for use or access in other locations. Anyone using or accessing the Services from other locations does so on their own initiative and is responsible for compliance with Philippines’ and local laws regarding online conduct and acceptable content, if and to the extent such laws are applicable. We reserve the right to limit the availability of the Services and/or the provision of any content, program, product, service or other feature to any person, geographic area, or jurisdiction, at any time and in our sole discretion, and to limit the quantities of any such content, program, product, service or other feature that we provide.</p>
<p class="has-line-data" data-line-start="18" data-line-end="19">Proprietary Rights</p>
<p class="has-line-data" data-line-start="20" data-line-end="21">The Services are owned and operated by Stock Knowledge. Unless otherwise explicitly specified by Stock Knowledge, all materials that are included in or otherwise a part of the Services, including past, present, and future versions, domain names, source and object code, the text, site design, logos, graphics, bibliographic and citation information, citation guides, icons, and book cover images, as well as the selection, assembly and arrangement thereof and the “look and feel” of the Services (collectively, ” Stock Knowledge Content“), are owned, controlled, or licensed by Stock Knowledge or Stock Knowledge’s third party partners. Stock Knowledge Content is protected from unauthorized use, copying and dissemination by copyright, trademark, patent, and other laws, rules, regulations and treaties. All rights in images of books or other publications included in the Services are reserved by the copyright owners of such materials. Portions of the bibliographic and citation content included in the Services are supplied by third parties. Any unauthorized use of Stock Knowledge Content is prohibited. Any unauthorized use of the materials appearing on the Services may violate copyright, trademark, patent, and other applicable laws, rules, regulations, and treaties, and could result in criminal or civil penalties.</p>
<p class="has-line-data" data-line-start="22" data-line-end="23">Your License to Use Stock Knowledge Content</p>
<p class="has-line-data" data-line-start="24" data-line-end="25">Subject to your compliance with these Terms of Use, Stock Knowledge grants you a limited, personal, non-exclusive, non-commercial, revocable and non-transferable license to view the Stock Knowledge Content. You may only use the Services for your own personal use. You agree not to view, copy, or procure content or information from the Services by automated means (such as scripts, bots, spiders, crawlers, or scrapers), or to use other data mining technology or processes to frame, mask, extract data or other materials from the Stock Knowledge Content (except as may be a result of standard search engine or Internet browser usage), unless formally authorized by Stock Knowledge under separate written agreement. No materials from the Services may be copied, reproduced, modified, republished, downloaded, uploaded, posted, transmitted, or distributed in any form or by any means without Stock Knowledge’s prior written permission or as expressly provided in these Terms of Use. When you download or use the Stock Knowledge Content as authorized by these Terms of Use, you must: (a) keep intact any and all copyright and other proprietary notices; (b) make no modifications to the Stock Knowledge Content; and © not copy or adapt any object code associated with the Services or reverse engineer, modify or attempt to discover any source code associated with the Services, or allow or assist any third party (whether or not for your benefit) to do so. All rights not expressly granted herein are reserved. Where you purchase a subscription or a license to access any Stock Knowledge Content, you may not share that subscription or license with others. Stock Knowledge may impose reasonable limits on your scope of access to Stock Knowledge Content, including limits on time or number of materials accessed or machines used to access such Content, to prevent unauthorized third party access to or use of that Content.</p>
<p class="has-line-data" data-line-start="26" data-line-end="27">Social Distribution and Widgets</p>
<p class="has-line-data" data-line-start="28" data-line-end="29">Stock Knowledge may allow you but only through express written permission to engage in certain personal uses of Stock Knowledge Content that include the ability to share certain Stock Knowledge Content with others (“Social Distribution“). For example, the Services may allow you to send certain Stock Knowledge Content to friends, display Stock Knowledge Content on your personal web site or post Stock Knowledge Content on a third party web site. You agree that you will not imply that you and Stock Knowledge are affiliated in any way or that Stock Knowledge approves of your comments. We reserve the right to revoke our permission for Social Distribution at any time and for any reason, and you agree to immediately cease Social Distribution upon notice of revocation and to comply with any terms we post in connection with the Social Distribution of Stock Knowledge Content.</p>
<p class="has-line-data" data-line-start="30" data-line-end="31">Similarly, the Services may provide content that you may choose to embed on your personal web page, third party web site or social networking site by pasting the HTML or other code provided by us (typically labeled as an embed code) (“Widgets“). Widgets are Stock Knowledge Content and subject to the limited, revocable license described above. We may discontinue providing the services necessary for the Widgets to operate or we may disable Widgets you have embedded at any time for any reason without any liability to you. You agree that our permission to you to use Widgets does not provide you (or any third party) with any intellectual property rights in or to the Widget or any Stock Knowledge Content made available via any Widget.</p>
<p class="has-line-data" data-line-start="32" data-line-end="33">NOTICE TO THIRD PARTY SITES: Any Stock Knowledge Content made available in connection with your site, or otherwise, by our Widgets, third party widgets or otherwise, is our exclusive property and no grant of any intellectual property rights is made by us. We retain the right to demand that you cease any use of Stock Knowledge Content upon notice.</p>
<p class="has-line-data" data-line-start="34" data-line-end="35">Digital Content</p>
<p class="has-line-data" data-line-start="36" data-line-end="37">If you receive as part of your order access codes, passwords or downloads for online eBooks or publisher created online digital services content (“Digital Content“), then, when activating the codes, downloading content or logging in to access or use Digital Content, you may be required to agree to certain additional terms and conditions (“Digital Content Terms“) before you may access the Digital Content. Read the Digital Content Terms for each Digital Content you rent or purchase, as different Digital Content may come with different restrictions or may be updated from time to time. If there is a conflict between the Digital Content Terms and these Terms of Use, the Digital Content Terms supersede the Terms of Use only to the extent of your use of the relevant Digital Content.</p>
<p class="has-line-data" data-line-start="38" data-line-end="39">User Content and Activities</p>
<p class="has-line-data" data-line-start="40" data-line-end="41">When you submit, post, upload, embed, display, communicate, link to, email or otherwise distribute or publish any review, problem, suggestion, idea, solution, question, answer, class notes, course outline bibliographic and citation information comment, testimonial, feedback, message, image, video, text, profile data or other material (“User Content“) to Stock Knowledge, any Stock Knowledge employee or contractor, or a Stock Knowledge Website, you grant Stock Knowledge and our affiliates, licensees, distributors, agents, representatives and other entities or individuals authorized by Stock Knowledge, a non-exclusive, worldwide, perpetual, unlimited, irrevocable, royalty-free, fully sublicensable (through multiple tiers) and fully transferable right to exercise any and all copyright, trademark, publicity, and database rights you have in the content, in any media known now or in the future, and to make, use, reproduce, copy, display, publish, exhibit, distribute, modify, sell, offer for sale, create derivative works based upon and otherwise use the User Content.</p>
<p class="has-line-data" data-line-start="42" data-line-end="43">Note that we may create, facilitate or display social advertisements, whereby your name, profile and photo may be used to advertise products and services to your network based on your use of the Services and your interactions with Stock Knowledge. You agree that Stock Knowledge may use your name and profile picture in connection with social ads to advertise products and services to your network based on your use of the Services and your interactions with Stock Knowledge and third parties through the Services.</p>
<p class="has-line-data" data-line-start="44" data-line-end="45">You further agree that Stock Knowledge is free to use any ideas or concepts contained in any User Content for any purposes whatsoever, including, without limitation, developing, manufacturing and marketing products and services; and creating informational articles, without any payment of any kind to you. You authorize Stock Knowledge to publish your User Content in a searchable format that may be accessed by users of the Services and the Internet. To the fullest extent permitted by law, you waive any moral rights you may have in any User Content you submit, even if such User Content is altered or changed in a manner not agreeable to you.</p>
<p class="has-line-data" data-line-start="46" data-line-end="47">Stock Knowledge is not required to host, display, or distribute, and may remove at any time, any User Content. Stock Knowledge reserves the right to change the format, sizing, and any other display specifications of the Content as it sees fit.</p>
<p class="has-line-data" data-line-start="48" data-line-end="49">You represent and warrant that (i) you own the User Content submitted by you on, through or in connection with the Services, or otherwise have the right to grant the licenses set forth in this section, and (ii) the posting of your User Content on, through or in connection with the Services and/or Linked Services does not violate the privacy rights, publicity rights, copyrights, contract rights or any other rights of any person or entity. Upon Stock Knowledge’s request, you will furnish Stock Knowledge any documentation, substantiation or releases necessary to verify your compliance with these Terms of Use.</p>
<p class="has-line-data" data-line-start="50" data-line-end="51">Except as otherwise described in the posted Privacy Policy, or other agreement on the Services presented at the time you provide your User Content (defined below), you agree that your User Content will be treated as non-confidential and non-proprietary and will not be returned. You acknowledge and agree that your relationship with Stock Knowledge is not a confidential, fiduciary, or other type of special relationship, and that your decision to submit any User Content does not place Stock Knowledge in a position that is any different from the position held by members of the general public, including with regard to your User Content. None of your User Content will be subject to any obligation of confidence on the part of Stock Knowledge.</p>
<p class="has-line-data" data-line-start="52" data-line-end="53">It is our policy not to accept or consider content, information, ideas, suggestions or other materials other than those we have specifically requested, to which certain specific terms, conditions and requirements may apply. This is to avoid any misunderstandings if your ideas are similar to those we have developed or are developing independently.</p>
<p class="has-line-data" data-line-start="54" data-line-end="55">You agree that Stock Knowledge has no obligation to monitor or enforce your intellectual property rights to your User Content but has the right to protect and enforce its and its licensees’ rights to your User Content. You further acknowledge and agree that, to the fullest extent permitted by applicable law, Stock Knowledge will not have any obligation to you with regard to User Content and that Stock Knowledge may or may not monitor, display or accept your User Content and may delete it at any time. We may, but are not obligated to, review User Content prior to posting it on or distributing it through the Services, or allowing them to be distributed through the Services. This includes private messages exchanged by you and other users through the Services. This “User Content and Activities” section shall survive any expiration or termination of your relationship with Stock Knowledge.</p>
<p class="has-line-data" data-line-start="56" data-line-end="57">Acceptable Use Policy</p>
<p class="has-line-data" data-line-start="58" data-line-end="59">You are solely responsible for the User Content you submit, through or in connection with our Services, and any material or information that you transmit to other users and for your interactions with other users. When you contribute, upload or otherwise provide User Content via the Services, you agree to comply with the following Community Usage Rules. In addition to removing such prohibited materials, Stock Knowledge may terminate the responsible accounts, and/or report such activities to law enforcement authorities as appropriate.</p>
<p class="has-line-data" data-line-start="60" data-line-end="61">Prohibited User Content includes, but is not limited to, material that Stock Knowledge determines:</p>
<p class="has-line-data" data-line-start="62" data-line-end="75">is patently offensive or promotes or otherwise incites racism, bigotry, hatred or physical harm of any kind against any group or individual;<br>
harasses or advocates harassment of another person;<br>
exploits people in a sexual or violent manner or contains nudity, excessive violence, or offensive subject matter or contains a link to an adult or otherwise objectionable website;<br>
posts information that poses or creates a privacy or security risk to any person;<br>
constitutes or promotes information that you know is false or misleading or promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libelous;<br>
constitutes or promotes an illegal or unauthorized copy of another person’s copyrighted work, such as providing pirated computer programs or links to them, providing information to circumvent manufacturer-installed copy-protect devices, or providing pirated music or links to pirated music files;<br>
involves the transmission of “junk mail,” “chain letters,” or unsolicited mass mailing, instant messaging, “spimming,” or “spamming”;<br>
contains restricted or password only access pages or hidden pages or images (those not linked to or from another accessible page) or solicits or is designed to solicit passwords or personal identifying information for commercial or unlawful purposes from other users;<br>
furthers or promotes any criminal activity or enterprise or provides instructional information about illegal activities including, but not limited to, making or buying illegal weapons or providing or creating computer viruses;<br>
involves commercial activities and/or sales without prior written consent from Stock Knowledge such as contests, sweepstakes, barter, advertising, or pyramid schemes;<br>
includes a photograph or video of another person that you have posted without that person’s consent;<br>
violates or attempts to violate the privacy rights, publicity rights, copyrights, patent rights, trademark rights, contract rights or any other rights of any person.<br>
Prohibited activities include, without limitation:</p>
<p class="has-line-data" data-line-start="76" data-line-end="87">unauthorized advertising to, or solicitation of, any user to buy or sell any products or services;<br>
circumventing or modifying, attempting to circumvent or modify, or encouraging or assisting any other person in circumventing or modifying any security technology or software that is part of our Services;<br>
activity that involves the use of viruses, bots, worms, or any other computer code, files or programs that interrupt, destroy or limit the functionality of any computer software or hardware, or otherwise permit the unauthorized use of or access to a computer or a computer network;<br>
modifying, copying, distributing, downloading, scraping or transmitting in any form or by any means, in whole or in part, any content from the Services;<br>
covering or obscuring the banner advertisements and/or safety features (e.g., report abuse button) on your personal profile page, or any Stock Knowledge page via HTML/CSS or any other means;<br>
any automated use of the Services, such as, but not limited to, using scripts to send messages or posts;<br>
interfering with, disrupting, or creating an undue burden on the Services or the networks or services connected to the Services;<br>
displaying an unauthorized commercial advertisement on your profile, or accepting payment or anything of value from a third person in exchange for your performing any commercial activity through the use of the Services on behalf of that person, such as placing commercial content on review posts or solutions, links to e-commerce sites not authorized by Stock Knowledge, or sending messages with a commercial purpose;<br>
activity unrelated or disruptive to the Services, such as intentionally distributing the wrong solutions to problems, submissions that force browsers to scroll horizontally, large blank or content-free submissions, “Bumping” multiple older topics (posting in them well after the last post), posting multiple identical or near-identical messages or topics, including “fad” topics, hard-to-read topic titles (e.g., ALL CAPS, AlTeRnAtE cApS, no spaces, no or excessive punctuation), or multiple hard-to-read or nonsensical messages in a single or multiple topics; or<br>
using the Services in a manner inconsistent with any applicable law.<br>
Service Modifications</p>
<p class="has-line-data" data-line-start="88" data-line-end="89">Stock Knowledge reserves the right, in our sole discretion, to make changes to or discontinue any of the Services at any time. Any description of the Services provided by Stock Knowledge is not a representation that the Services are working or will always work in that manner, as Stock Knowledge is continuously updating the Services, and these updates may not always be reflected in the Terms of Use.</p>
<p class="has-line-data" data-line-start="90" data-line-end="91">Mobile Use</p>
<p class="has-line-data" data-line-start="92" data-line-end="93">The Services may offer features and services that are available to you via your mobile device. These features and services may include, without limitation, the ability to upload content to the Services, receive messages from the Services, download applications to your mobile phone or access features from the Services (collectively, the “Mobile Features“). We may charge for Mobile Features and these charges will be disclosed prior to completion of registration for the Mobile Feature. Also, standard messaging, data and other fees may be charged by your carrier. Carrier fees and charges will appear on your mobile bill or be deducted from your pre-paid balance. Your carrier may prohibit or restrict certain Mobile Features and certain Mobile Features may be incompatible with your carrier or mobile device. Contact your carrier with questions regarding these issues.</p>
<p class="has-line-data" data-line-start="94" data-line-end="95">If you change or terminate your mobile account, you agree to promptly update your Stock Knowledge account information so that any messages or notices from Stock Knowledge regarding the Services are sent to you and not to the person who is assigned your old number.</p>
<p class="has-line-data" data-line-start="96" data-line-end="97">For any of our mobile apps, you agree that the third party store or platform through which our apps are available (including, without limitation, the Apple App Store) is not liable to you in connection with our apps. If you use any ISBN scan feature of the Services, you are responsible for verifying the accuracy of the scanned code before relying on it.</p>
<p class="has-line-data" data-line-start="98" data-line-end="99">Email and Text Message Notifications</p>
<p class="has-line-data" data-line-start="100" data-line-end="101">Notifications or receipts from Stock Knowledge will be delivered to you by email at the address you provided to Stock Knowledge when you created your account or as later updated. You may also opt to receive text message reminders from Stock Knowledge, as a courtesy to you. Please review our text message mobile disclosures, which are incorporated into the Terms of Use. Stock Knowledge may contact you, sometimes through an automated or pre-recorded message, using the phone numbers you provide to Stock Knowledge, including wireless numbers, to remind you that rental books are due to be returned or otherwise provide the Services. You are still responsible for compliance with the Terms of Use, including, e.g., timely return of your books, whether or not you receive such reminders via email, text or otherwise. Stock Knowledge will not ask you for your personal information, account username, and password, or any of your credit or debit card information via email or text message. If you receive such an email or text message purportedly from Stock Knowledge, it is fraudulent and Stock Knowledge will have no responsibility for any misuse of any information you provide as a result.</p>
<p class="has-line-data" data-line-start="102" data-line-end="103">Account Cancellation</p>
<p class="has-line-data" data-line-start="104" data-line-end="105">You may request cancellation of your account at any time throughout your use of our Services. To the fullest extent permissible under applicable law, your account will only be cancelled and closed after you have returned all books that have been rented to you (if any) and all transactions have been processed including payment of assessed penalties or the cashing of any refund check, if applicable. Stock Knowledge may cancel your account in its sole discretion any reason, including but not limited to inactivity or misuse. Even if your account is cancelled, your photos, bibliographic and citation information, comments, likes, friendships, and any other data you have shared via the Services may persist within the Service after cancellation of your account (for example, if your content has been reshared by others), subject to the provisions of our Privacy Policy on the retention of personal information.</p>
<p class="has-line-data" data-line-start="106" data-line-end="107">Credit/Debit Card Processing &amp; Payments</p>
<p class="has-line-data" data-line-start="108" data-line-end="109">Stock Knowledge may require users of the Services to provide a valid credit or debit card tied to an account at a financial institution when they register for an account (to ensure users are able to make applicable payments to Stock Knowledge) or upon ordering products or services. If a payment card is required, you are responsible for ensuring that a valid credit or debit card is associated with your Stock Knowledge account at all times (either the original card or a replacement). To confirm your card is valid, Stock Knowledge may initiate a “pending” charge for fifty pesos (Php 50.00) on the account. This charge will not be confirmed and, therefore, you will not be charged and it will simply disappear from your financial statement (usually within seven days – check with your financial institution for additional information). Please be aware that this Php.50.00 pending charge may be initiated each time you edit the card information for your account or place an order that cannot be processed. Where your billing address is requested, you must provide the address and phone number your financial institution has on record, as well as the card’s security code (e.g., CVC, CVV, CID). Stock Knowledge will make reasonable efforts to process your transactions in a timely manner, but we make no guarantees regarding the processing time for charges. Stock Knowledge will store your credit or debit card information and you hereby acknowledge and agree that Stock Knowledge may charge you for, and you will pay for, any charges specified on the Services and for any auto-extension or unreturned, lost, stolen, or damaged books associated with your account under the terms of your book rental and in accordance with the General Policies. For any books or other materials kept beyond the applicable rental term, you agree to be charged the applicable late fees as set out in our General Policies. For any books or other rental materials that are never returned (an item is deemed “never returned” if it has not been returned in the period posted in our General Polices) or that are returned damaged, you agree to be charged for the value of the item(s) as set out in our General Policies. Stock Knowledge reserves the right to place you into collections if you fail to timely pay for the products and services ordered through the Services; collections may be done by Stock Knowledge or a third party on Stock Knowledge’s behalf. You also agree that we may, at our discretion, send your account to a collection agency, and recover our reasonable costs of collection from you, if you fail to pay all fees due and owing to Stock Knowledge. For security reasons or to otherwise confirm a financial instrument or payment, Stock Knowledge may delay mailings of books or otherwise delay providing payments or services even if such delay impacts a guaranteed delivery date.</p>
<p class="has-line-data" data-line-start="110" data-line-end="111">Third Party Links, Content and Applications</p>
<p class="has-line-data" data-line-start="112" data-line-end="113">There may be links from the Services, or from communications you receive from the Services, to third party web sites or online features. The Services also may include third party content that we do not control, maintain or endorse.</p>
<p class="has-line-data" data-line-start="114" data-line-end="115">Functionality on the Services may also permit interactions between the Services and a third party web site or online feature, including applications that connect the Services or your profile on the Services with a third party site. For example, the Services may include a button enabling you to indicate, on your social networking page, that you “like” a specific product on the Services, or a feature that lets you post to your social networking page a link to a specific product or the ability to share content from the Services or your User Content with a third party, which may be publicly posted on that third party’s web site. Using this functionality typically requires you to login to your account on the third party website. We do not control any of these third party sites or any of their content. Neither Stock Knowledge nor its service providers are responsible for the practices of any third party. Accordingly, you expressly acknowledge and agree that we make no representations or warranties about the completeness, accuracy, or existence of any advertising, products, or other materials on or available from third party sites or online features and any reliance placed by you on such materials is at your own risk. YOUR CORRESPONDENCE AND BUSINESS DEALINGS WITH THIRD PARTIES FOUND THROUGH THE SERVICES INCLUDING, WITHOUT LIMITATION, THE PAYMENT AND DELIVERY OF PRODUCTS AND SERVICES, AND ANY TERMS, CONDITIONS, WARRANTIES AND REPRESENTATIONS ASSOCIATED WITH ANY SUCH DEALINGS, ARE SOLELY BETWEEN YOU AND THE THIRD PARTY.</p>
<p class="has-line-data" data-line-start="116" data-line-end="117">Linking Policy</p>
<p class="has-line-data" data-line-start="118" data-line-end="119">Stock Knowledge grants you the revocable permission to link to the web sites on which these Terms of Use are posted; provided, however, that any link to such a web site: (a) must not frame or create a browser or border environment around any of the content on such web sites or otherwise mirror any part of such web sites; (b) must not imply that Stock Knowledge or the Services are endorsing or sponsoring any third party or its products or services, unless Stock knowledge has given the third party prior written consent; © must not present false information about, or disparage, tarnish, or otherwise, in Stock Knowledge’s sole opinion, harm Stock Knowledge or its products or services; (d) must not use any Stock Knowledge trademarks without the prior written permission from Stock Knowledge; (e) must not contain content that could be construed as distasteful, offensive or controversial or otherwise objectionable (in Stock Knowledge’s sole opinion); and (f) must be owned and controlled by you or the person or entity placing the link, or otherwise permit you to enable such link subject to these Terms of Use. By linking to a Stock Knowledge Website, you agree that you do and will continue to comply with the above linking requirements.</p>
<p class="has-line-data" data-line-start="120" data-line-end="121">Notwithstanding anything to the contrary contained in these Terms of Use, Stock Knowledge reserves the right to prohibit linking to any Stock Knowledge Website for any reason in our sole and absolute discretion.</p>
<p class="has-line-data" data-line-start="122" data-line-end="123">Course Searches and Other Information Specific to an Academic Institution</p>
<p class="has-line-data" data-line-start="124" data-line-end="125">We may tie your Stock Knowledge experience to information about the school you have identified to Stock Knowledge. For certain schools, the Services enable you to search and retrieve information about the materials required for particular courses. Please be aware that course information and assigned materials may change from time to time, and Stock Knowledge may not receive updated information from the school in a timely manner. Stock Knowledge is not responsible for any errors in the information provided in the course searches on the Services. Where specific school names or information relate to a specific school are displayed, they do not imply any endorsement or approval by the school. Except where specifically stated, Stock Knowledge has no affiliation with nor endorsement from any academic institution, and school names and information are used on the Services only to the extent necessary to organize, identify and permit use of information and sections of the Services that may be tailored to students of a particular school, or for other lawful uses.</p>
<p class="has-line-data" data-line-start="126" data-line-end="127">Categories of Users</p>
<p class="has-line-data" data-line-start="128" data-line-end="129">You may use Stock Knowledge’s homework help services as a “Member” or a “Visitor.” “Members” may include a variety of designated levels of members who may be charged for services according to the terms of the particular offer, or registered free members (a “Free Member“), or other membership levels. “Visitors” are users that have not registered for an account with access to and use of certain aspects of the homework help services, which may be restricted and only available to certain Members. The membership levels, the benefits and pricing of each level of membership may vary and are subject to change at any time, please read the terms of any particular level of membership carefully before accepting it. Stock Knowledge may modify these levels and benefits from time to time, and each such modification is effective as soon as we post it on the relevant Services except to the extent that your particular pricing structure is established in writing for a period of time in the future, such as an annual plan. It is therefore important that you review the membership page regularly to ensure you are aware of any such changes.</p>
<p class="has-line-data" data-line-start="130" data-line-end="131">Homework Help, Study Guide and Note Usage</p>
<p class="has-line-data" data-line-start="132" data-line-end="133">Stock Knowledge’s homework help, study and note services are available merely as informational and study aids and should not be considered substitutes for applicable coursework, homework, class and lecture requirements, assignments and related materials. In using the Services, you specifically agree not to use, claim or submit as your own any portion of the help materials. Stock Knowledge does not guarantee the accuracy or quality of answers or other study material that appear on the Services, some of which may be posted by other users. You further agree the Services may present information that is incorrect or inconsistent when compared to similar content and materials, including solutions and their methodologies, provided or preferred by publishers of applicable problems or instructors of applicable courses.</p>
<p class="has-line-data" data-line-start="134" data-line-end="135">Outlines, Study Guides and Notes</p>
<p class="has-line-data" data-line-start="136" data-line-end="137">Stock Knowledge may permit users to upload and in some cases sell content for the purpose of aiding others in the education and learning process. Users may not post content owned or created (except if it is in the public domain) by another person and hereby represent and warrant that: (i) each was created by the user and the user is the sole owner of all content posted to Services sites and all rights in such content (except for public domain content), including, without limitation, copyright and (ii) the posting of Content on or through the Services will not breach the privacy rights, publicity rights, copyrights, contract rights, intellectual property rights or any other rights of any third-party. Users agree to pay for all royalties, fees, and any other monies owing to any third-party for any content provided by you to the Services. Users of the Services agree to exclude from such content any documents, records or files made accessible to them by (a) your school, professor or other instructor, (b) any board of examination, © any author or publisher whose works have been used as part of studies or (d) any co-student.</p>
<p class="has-line-data" data-line-start="138" data-line-end="139">In creating study related content, students must respect any intellectual property rights that others may have in content. All content posted on the Services must be independently created, transformative and non-derivative. It should not be a transcript or recording of another’s independent efforts, nor should it copy from materials purchased from or created by others. It should go beyond simply summarizing material covered in class or in written or recorded materials, but include information raised by students in or outside of class, and independent thought, analysis and commentary. Class notes, for example, must be substantially rewritten after class and include independent thought and analysis, research and information; notes that use a lecturer’s words or that are not carefully reviewed, rethought and rewritten after class are not useful to or appreciated by students, and not permitted on the Services.</p>
<p class="has-line-data" data-line-start="140" data-line-end="141">Schools may have their own policies that place restrictions on a student’s ability to make commercial use of study materials, even otherwise lawful materials that the student has independently created. You are responsible for becoming familiar with such policies and abiding by them, and discontinuing the use of any Services if such use is contrary to your school policy or the instruction of your professor.</p>
<p class="has-line-data" data-line-start="142" data-line-end="143">Class notes and study guides are solely for the specific use of students in the designated class for which they are created. Individuals who are not registered for a class may not purchase study guides, class notes or outlines for that class. Check the accuracy of all information from study guides, class notes, answers and outlines – to the fullest extent permitted under applicable law, Stock Knowledge does not guarantee their accuracy or completeness, they are simply an aid to the study process.</p>
<p class="has-line-data" data-line-start="144" data-line-end="145">Learning Courses</p>
<p class="has-line-data" data-line-start="146" data-line-end="147">Stock Knowledge may offer third party learning videos and instructional material. Stock Knowledge does not hire or employ Instructors. We are not responsible for the content of such third party materials, nor the advice provided in such materials. We do not control such materials and, as such, to the fullest extent permitted under applicable law, do not guarantee their reliability, validity, accuracy or truthfulness. Completing such courses may provide you with skills and experience that may help your career prospects, but as noted above, there are a large number of factors tied to your career and completing such courses is no guarantee of improved employability or enhanced career prospects.</p>
<p class="has-line-data" data-line-start="148" data-line-end="149">Test Prep Services</p>
<p class="has-line-data" data-line-start="150" data-line-end="151">Stock Knowledge may offer services to help students prepare for a variety of standardized tests. Any test prep courses branded as Stock Knowledge’s and offered through the Stock Knowledge Websites are copyrighted and the property of Stock Knowledge, Corp., and are for the sole personal non-commercial use of individuals who register with Stock Knowledge and pay for such services, subject to these Terms of Use. Stock Knowledge test prep services are not endorsed nor affiliated with the companies who offer the test itself.</p>
<p class="has-line-data" data-line-start="152" data-line-end="153">Bibliography and Citation Services</p>
<p class="has-line-data" data-line-start="154" data-line-end="155">Stock Knowledge may offer citation, bibliography and plagiarism checker services, including but not limited to, EasyBib, BibMe, Cite This For Me, Citation Machine, Normas APA and other writing tools through the Stock Knowledge Websites to help students and their educators develop student reading and writing skills. To the fullest extent permitted under applicable law, Stock Knowledge does not guarantee the accuracy or quality of content that appears on the Services in connection with such citation, bibliography and plagiarism checker services and other writing tools.</p>
<p class="has-line-data" data-line-start="156" data-line-end="157">Tutoring Services</p>
<p class="has-line-data" data-line-start="158" data-line-end="159">Stock Knowledge may also make online tutoring services available through Stock Knowledge Websites (“Tutoring Services”). The following sections that include “Tutors” or “Tutoring” in the heading relate specifically and only to Tutoring Services. If there is any conflict between this Tutoring Services section and these Terms of Use, the tutoring sections control within respect to the Tutoring Services. Tutoring sections are not applicable to other Stock Knowledge Services or Websites or any area outside of the tutoring services websites.</p>
<p class="has-line-data" data-line-start="160" data-line-end="161">You understand and agree that Stock Knowledge acts only as an interface to facilitate communications between users and Tutors and to collect payment from users on behalf of Tutors. THE TUTORINGSERVICES COMPRISE AN ONLINE PLATFORM WHICH FACILITATES THE CONNECTION BETWEEN USERS AND TUTORS FEATURED ON THE SITE AND VIA THE SERVICES. YOU UNDERSTAND AND AGREE THAT STOCK KNOWLEDGE IS NOT A PARTY TO ANY AGREEMENTS ENTERED INTO BETWEEN USERS AND TUTORS. TUTORS ARE INDEPENDENT CONTRACTORS, NOT EMPLOYEES OR AGENTS OF STOCK KNOWLEDGE. STOCK KNOWLEDGE HAS NO CONTROL OVER THE LESSON SERVICES OR CONDUCT OF USERS, TUTORS AND OTHER USERS OF THE SITE AND SERVICES.</p>
<p class="has-line-data" data-line-start="162" data-line-end="163">Certain areas of the Stock Knowledge Websites (and your access to or use of certain Services or Stock Knowledge Content) including any policy pages may have different terms and conditions posted or may require you to agree with and accept additional terms and conditions. If there is a conflict between these User Terms of Service and terms and conditions or policies posted for a specific area of the Stock Knowledge Websites, Services or Stock Knowledge Content, the later terms and conditions will take precedence with respect to your use of or access to that area of the Stock Knowledge Websites, Services or Stock Knowledge Content, as applicable. Policies relating to Tutoring Services may be found here, and are hereby incorporated into this Agreement.</p>
<p class="has-line-data" data-line-start="164" data-line-end="165">PLEASE NOTE THAT STOCK KNOWLEDGE DOES NOT CONFIRM THE INFORMATION IN A TUTOR’S PROFILE, THEIR COMPETENCY, THEIR BACKGROUND NOR THEIR PROFICIENCY IN THE SUBJECT MATTERS WHERE THEY OFFER THEIR SERVICES. STOCK KNOWLEDGE CANNOT AND DOES NOT CONTROL THE SERVICES PERFORMED BY TUTORS FOR USERS, OR THE ACTIONS OF ANY TUTORS, USERS OR OTHER USERS OF THE SITE AND SERVICES. STOCK KNOWLEDGE IS NOT RESPONSIBLE FOR THE ACTIONS OF TUTORS, USERS, THIRD PARTIES AND OTHER USERS OF THE SITE AND SERVICES. ACCORDINGLY, ANY MEETINGS (VIRTUAL OR OTHERWISE) BETWEEN USERS, TUTORS OR ANY OTHER THIRD PARTIES AND ANY PURCHASES OF LESSON SERVICES PROVIDED BY TUTORS ARE DONE AT THE USER’S RISK, TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW.</p>
<p class="has-line-data" data-line-start="166" data-line-end="167">Stock Knowledge is not responsible for the use or exchange of any information or files between Tutors and users. Further, Stock Knowledge does not control, nor is it responsible for, the truth, accuracy, completeness, safety, timeliness, quality, legality or applicability of anything said or written by Tutors or users. Accordingly, we encourage you to communicate directly with others you may come into contact with as a result of your use of the Stock Knowledge Websites and Services.</p>
<p class="has-line-data" data-line-start="168" data-line-end="169">Interaction with Tutors and Use of Lesson Services</p>
<p class="has-line-data" data-line-start="170" data-line-end="171">Stock Knowledge acts as a technology service that facilitates provision of Lesson Services between users and Tutors and does not make decisions related to the provision of, or otherwise exercise control or supervision over, Lesson Services or contents thereof. Stock Knowledge does not endorse any Tutor and you are responsible for determining and confirming the identity and suitability of the Tutors interacted with as a result of your use, or use by any third party, of the Stock Knowledge Websites and Services. Stock Knowledge does not endorse any Tutors. In addition, although the Stock Knowledge Tutor Terms of Service require Tutors to provide accurate information, we cannot confirm or test any Tutor’s purported identity or academic qualifications or experience. We are not your agent or the agent of any Tutor. If you ever believe that another User or Tutor has violated law or is defrauding, threatening or endangering anyone, Stock Knowledge urges you to immediately contact the police directly for help.</p>
<p class="has-line-data" data-line-start="172" data-line-end="173">Tutoring Attachments</p>
<p class="has-line-data" data-line-start="174" data-line-end="175">Your use of the Stock Knowledge Websites or Services may involve the exchange of file attachments between you and a Stock Knowledge Tutor. Stock Knowledge is not responsible or liable for the content of such attachments, and such attachments may be viewed by other Stock Knowledge users, or by the public generally. You acknowledge sole responsibility for and assume the risk arising from your downloading any such attachments and posting such attachments.</p>
<p class="has-line-data" data-line-start="176" data-line-end="177">End of Tutoring Specific Section</p>
<p class="has-line-data" data-line-start="178" data-line-end="179">Disclaimer of Warranties</p>
<p class="has-line-data" data-line-start="180" data-line-end="181">TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, THE STOCK KNOWLEDGE WEBSITES AND SERVICES ARE PROVIDED ON AN “AS IS,” “AS AVAILABLE,” AND “WITH ALL FAULTS” BASIS AND WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMISSIBLE UNDER APPLICABLE LAW, STOCK KNOWLEDGE AND ITS SUBSIDIARIES, DIRECTORS, EMPLOYEES, MANAGERS, OFFICERS, AGENTS, REPRESENTATIVES, VENDORS AND THIRD PARTY LICENSORS OF CONTENT SOLD THROUGH STOCK KNOWLEDGE (COLLECTIVELY THE “STOCK KNOWLEDGE PARTIES“) SPECIFICALLY MAKE NO REPRESENTATIONS, WARRANTIES, OR ENDORSEMENTS OF ANY KIND, WHETHER EXPRESS OR IMPLIED, AS TO (A) THE STOCK KNOWLEDGE WEBSITES OR THE SERVICES; (B) THE STOCK KNOWLEDGE CONTENT; © USER CONTENT; AND/OR (D) SECURITY ASSOCIATED WITH THE TRANSMISSION OF INFORMATION TO STOCK KNOWLEDGE OR VIA THE SERVICES. IN ADDITION, TO THE FULLEST EXTENT PERMISSIBLE BY APPLICABLE LAW, THE STOCK KNOWLEDGE PARTIES DISCLAIM ALL WARRANTIES, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING, BUT NOT LIMITED TO, WARRANTIES OF FITNESS FOR A PARTICULAR PURPOSE, OF MERCHANTABILITY, NON-INFRINGEMENT, TITLE, CUSTOM, TRADE, QUIET ENJOYMENT, AND SYSTEM.</p>
<p class="has-line-data" data-line-start="182" data-line-end="183">TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, THE STOCK KNOWLEDGE PARTIES SPECIFICALLY DO NOT WARRANT THAT THE SERVICES WILL BE ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE SERVICES OR THE SERVER, NETWORK OR OTHER SOFTWARE AND EQUIPMENT THAT MAKES THEM AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, STOCK KNOWLEDGE DOES NOT MAKE ANY REPRESENTATIONS OR WARRANTIES REGARDING THE CONTENT OF ITS PRODUCTS, WEBSITES OR SERVICES, OR REGARDING THE RESULTS OF THE USE OF THE SERVICES IN TERMS OF THEIR COMPLETENESS, CORRECTNESS, ACCURACY, RELIABILITY, USEFULNESS OR OTHERWISE, UNLESS SPECIFICALLY SET OUT ON THE SERVICES. YOU ACKNOWLEDGE THAT YOUR USE OF THE SERVICES IS AT YOUR SOLE RISK. TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, THE STOCK KNOWLEDGE PARTIES DO NOT WARRANT THAT YOUR USE OF THE SERVICES IS LAWFUL IN ANY PARTICULAR JURISDICTION, AND THE STOCK KNOWLEDGE PARTIES SPECIFICALLY DISCLAIM SUCH WARRANTIES.</p>
<p class="has-line-data" data-line-start="184" data-line-end="185">BY ACCESSING OR USING THE SERVICES YOU REPRESENT AND WARRANT THAT YOUR ACTIVITIES ARE LAWFUL IN EVERY JURISDICTION WHERE YOU ACCESS OR USE THE SERVICES.</p>
<p class="has-line-data" data-line-start="186" data-line-end="187">THE STOCK KNOWLEDGE PARTIES ARE NOT RESPONSIBLE FOR THE USER CONTENT, ACCURACY OR OPINIONS EXPRESSED IN USER CONTENT POSTED OR PROVIDED BY THIRD PARTIES ON THE SERVICES OR LINKED SERVICES, AND SUCH SERVICES ARE NOT NECESSARILY INVESTIGATED, MONITORED OR CHECKED FOR ACCURACY OR COMPLETENESS BY STOCK KNOWLEDGE. INCLUSION OF ANY LINKED WEBSITE OR FEATURE ON THE SERVICES DOES NOT IMPLY APPROVAL OR ENDORSEMENT OF THE LINKED WEBSITE OR FEATURE BY STOCK KNOWLEDGE. POSTS AND LINKED SERVICES CREATED AND POSTED BY USERS ON, THOUGH OR IN CONNECTION WITH THE SERVICES MAY CONTAIN LINKS TO OTHER WEBSITES OR SERVICES. STOCK KNOWLEDGE TAKES NO RESPONSIBILITY FOR THIRD PARTY ADVERTISEMENTS OR LINKED SERVICES THAT ARE POSTED ON, THROUGH OR IN CONNECTION WITH THE SERVICES OR LINKED SERVICES, NOR DOES IT TAKE ANY RESPONSIBILITY FOR THE GOODS OR SERVICES PROVIDED BY THESE THIRD PARTIES. THIS “DISCLAIMERS” SECTION SHALL SURVIVE ANY EXPIRATION OR TERMINATION OF YOUR RELATIONSHIP WITH STOCK KNOWLEDGE.</p>
<p class="has-line-data" data-line-start="188" data-line-end="189">Limitations of Liability; Waiver</p>
<p class="has-line-data" data-line-start="190" data-line-end="191">IN NO EVENT SHALL THE STOCK KNOWLEDGE PARTIES BE LIABLE FOR ANY INDIRECT, ECONOMIC, SPECIAL, INCIDENTAL OR CONSEQUENTIAL LOSSES OR DAMAGES RELATED TO: (A) THE SERVICES; (B) THE STOCK KNOWLEDGE CONTENT; © USER CONTENT; (D) YOUR USE OF, INABILITY TO USE, OR THE PERFORMANCE OF THE SITE; (E) ACTION TAKEN IN CONNECTION WITH AN INVESTIGATION BY THE STOCK KNOWLEDGE PARTIES OR LAW ENFORCEMENT AUTHORITIES REGARDING YOUR USE OF THE SITE; (F) ACTION TAKEN IN CONNECTION WITH COPYRIGHT OR OTHER INTELLECTUAL PROPERTY OWNERS; (G) ANY ERRORS OR OMISSIONS IN THE SERVICES’ TECHNICAL OPERATION; OR (H) ANY DAMAGE THAT RESULTS FROM EVENTS BEYOND OUR REASONABLE CONTROL, SUCH AS DAMAGES TO ANY USER’S COMPUTER, MOBILE DEVICE, OR OTHER EQUIPMENT OR TECHNOLOGY INCLUDING, WITHOUT LIMITATION, DAMAGE FROM ANY SECURITY BREACH OR FROM ANY VIRUS, BUGS, TAMPERING, FRAUD, ERROR, OMISSION, INTERRUPTION, DEFECT, DELAY IN OPERATION OR TRANSMISSION, COMPUTER LINE OR NETWORK FAILURE OR ANY OTHER TECHNICAL OR OTHER MALFUNCTION, INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOST PROFITS, LOSS OF GOODWILL, LOSS OF DATA, WORK STOPPAGE, ACCURACY OF RESULTS, OR COMPUTER FAILURE OR MALFUNCTION, EVEN IF FORESEEABLE OR EVEN IF THE STOCK KNOWLEDGE PARTIES HAVE BEEN ADVISED OF OR SHOULD HAVE KNOWN OF THE POSSIBILITY OF SUCH DAMAGES. IN NO EVENT WILL THE STOCK KNOWLEDGE PARTIES TOTAL LIABILITY TO YOU FOR ALL DAMAGES, LOSSES OR CAUSES OR ACTION EXCEED THE AMOUNTS PAID BY YOU, IF ANY, TO STOCK KNOWLEDGE IN THE PAST SIX MONTHS, OR PHP. 12,500.00, WHICHEVER IS GREATER. THE PRIOR LIMITATION ON DAMAGES IS NOT INTENDED TO LIMIT THE STOCK KNOWLEDGE PARTIES’ OBLIGATION TO PAY PREVAILING PARTY COSTS OR FEES IF RECOVERABLE PURSUANT TO APPLICABLE LAW. THE LIMITATIONS SET FORTH IN THIS SECTION WILL NOT LIMIT OR EXCLUDE THE STOCK KNOWLEDGE PARTIES’ LIABILITY FOR PERSONAL INJURY OR PROPERTY DAMAGE CAUSED BY THE STOCK KNOWLEDGE PARTIES, OR FOR THE STOCK KNOWLEDGE PARTIES’ GROSS NEGLIGENCE, FRAUD OR INTENTIONAL, WILLFUL, MALICIOUS OR RECKLESS MISCONDUCT. THIS SECTION SHALL SURVIVE ANY EXPIRATION OR TERMINATION OF YOUR RELATIONSHIP WITH STOCK KNOWLEDGE.</p>
<p class="has-line-data" data-line-start="192" data-line-end="193">YOU AGREE THAT IN THE EVENT YOU INCUR ANY DAMAGES, LOSSES OR INJURIES THAT ARISE OUT OF THE STOCK KNOWLEDGE PARTIES’ ACTS OR OMISSIONS, THE DAMAGES, IF ANY, CAUSED TO YOU ARE NOT IRREPARABLE OR SUFFICIENT TO ENTITLE YOU TO AN INJUNCTION PREVENTING ANY EXPLOITATION OF ANY WEB SITE, PROPERTY, PRODUCT, SERVICE, OR OTHER STOCK KNOWLEDGE CONTENT OWNED OR CONTROLLED BY THE STOCK KNOWLEDGE PARTIES, AND YOU WILL HAVE NO RIGHTS TO ENJOIN OR RESTRAIN THE DEVELOPMENT, PRODUCTION, DISTRIBUTION, ADVERTISING, EXHIBITION OR EXPLOITATION OF ANY WEB SITE, PROPERTY, PRODUCT, SERVICE, OR OTHER STOCK KNOWLEDGE CONTENT OWNED OR CONTROLLED BY THE STOCK KNOWLEDGE PARTIES.</p>
<p class="has-line-data" data-line-start="194" data-line-end="195">BY ACCESSING THE SERVICES, YOU UNDERSTAND THAT YOU MAY BE WAIVING RIGHTS WITH RESPECT TO CLAIMS THAT ARE AT THIS TIME UNKNOWN OR UNSUSPECTED, AND IN ACCORDANCE WITH SUCH WAIVER, YOU ACKNOWLEDGE THAT YOU HAVE READ AND UNDERSTAND, AND HEREBY EXPRESSLY WAIVE, THE BENEFITS OF SECTION 1542 OF THE CIVIL CODE OF CALIFORNIA, AND ANY SIMILAR LAW OF ANY STATE OR TERRITORY, WHICH PROVIDES AS FOLLOWS: “A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH IF KNOWN BY HIM MUST HAVE MATERIALLY AFFECTED HIS SETTLEMENT WITH THE DEBTOR.”</p>
<p class="has-line-data" data-line-start="196" data-line-end="197">Indemnity</p>
<p class="has-line-data" data-line-start="198" data-line-end="199">To the fullest extent permitted by applicable law, you agree to defend, indemnify and hold harmless the Stock Knowledge Parties from and against any and all loss, liability, damages, judgments, claims, demands, costs, investigations, settlements, and expenses (including, without limitation, reasonable attorneys’ fees) arising out of or directly or indirectly relating to (a) your User Content; (b) your use of the Services or activities in connection with the Services; © your breach or anticipatory breach of these Terms of Use; (d) your violation of any laws, rules, regulations, codes, statutes, ordinances or orders of any governmental and quasi-governmental authorities, including, without limitation, all regulatory, administrative and legislative authorities; (e) information or material transmitted through your computer, even if not submitted by you, that infringes, violates or misappropriates any copyright, trademark, trade secret, trade dress, patent, publicity, privacy or other right of any person or defames any person; (f) any misrepresentation made by you; or (g) the Stock Knowledge Parties’ use of your information or User Content as permitted under these Terms of Use, the Privacy Policy, or any other written agreement between you and Stock Knowledge. You will cooperate as fully required by the Stock Knowledge Parties in the defense of any claim. The Stock Knowledge Parties reserve the right to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, and you will not in any event settle any claim without the prior written consent of a duly authorized employee of the Stock knowledge Parties. These indemnity obligations shall survive any expiration or termination of your relationship with Stock Knowledge.</p>
<p class="has-line-data" data-line-start="200" data-line-end="201">Export</p>
<p class="has-line-data" data-line-start="202" data-line-end="203">Software related to or made available by the Services may be subject to Philippines export controls. Thus, no software from the Services may be downloaded, exported or re-exported into (a) a national or resident any other country to which the Philippines has embargoed goods; (b) an individual to which Philippine government has denied any access into the country. By downloading any software related to Stock Knowledge Websites, you represent and warrant that you are not located in, under the control of, or a national or resident of, any such country or on any such list. Further, by using any of the Services, you represent and warrant that you are not on any Philippine government list of restricted or prohibited persons with whom a Philippines company may do business.</p>
<p class="has-line-data" data-line-start="204" data-line-end="205">Reporting Copyright and Other Intellectual Property Violations</p>
<p class="has-line-data" data-line-start="206" data-line-end="207">We at Stock Knowledge Corp. respect the intellectual property rights of others and take the protection of copyrights and other intellectual property seriously. Only the intellectual property rights owner or person authorized to act on behalf of the owner can report potentially infringing content. If you believe your work has been infringed through the Services, please notify us at <a href="mailto:legal@theknowledgetools.com"><span class="__cf_email__" data-cfemail="462a2321272a06322e232d2829312a232221233229292a356825292b">legal@theknowledgetools.com</span></a>.</p>
<p class="has-line-data" data-line-start="208" data-line-end="216">Your contact information, including name, address, telephone number, and e-mail address;<br>
A description of the copyrighted work you claim has been infringed (including, e.g., the title, ISBN and other bibliographic information for books);<br>
A reasonably specific description of where the allegedly infringing material is located on the Services (including, e.g., the URL);<br>
A statement by you that you have a good-faith belief that the allegedly infringing material is not authorized by the copyright owner, its agent, or the law;<br>
Your electronic or physical signature;<br>
A statement by you, made under penalty of perjury, that the information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner’s behalf; and<br>
Information reasonably sufficient to permit us to contact the complaining party.<br>
NOTE: This contact information is for inquiries regarding potential copyright and other infringement only.</p>
<p class="has-line-data" data-line-start="217" data-line-end="218">It is often difficult to determine if your intellectual property rights have been violated. We may request additional information before we remove any infringing material. If a dispute develops as to the correct owner of the rights in question, we reserve the right to remove your content along with that of the alleged infringer pending resolution of the matter.</p>
<p class="has-line-data" data-line-start="219" data-line-end="220">Stock Knowledge will provide you with notice if your materials have been removed based on a third party complaint of alleged infringement of the third party’s intellectual property rights.</p>
<p class="has-line-data" data-line-start="221" data-line-end="222">IF YOU KNOWINGLY MISREPRESENT THAT MATERIAL IS OR IS NOT INFRINGING, YOU MAY BE SUBJECT TO CIVIL PENALTIES. THESE INCLUDE MONETARY DAMAGES, COURT COSTS, AND ATTORNEYS’ FEES INCURRED BY STOCK KNOWLEDGE, BY ANY COPYRIGHT OWNER, OR BY ANY COPYRIGHT OWNER’S LICENSEE THAT IS INJURED AS A RESULT OF RELIANCE UPON YOUR MISREPRESENTATION. YOU MAY ALSO BE SUBJECT TO CRIMINAL PROSECUTION FOR PERJURY. You agree we may provide your notice to the provider of the allegedly infringing material.</p>
<p class="has-line-data" data-line-start="223" data-line-end="224">We have a policy of terminating accounts of users who repeatedly and intentionally infringe the intellectual property rights of others.</p>
<p class="has-line-data" data-line-start="225" data-line-end="226">Legal Disputes</p>
<p class="has-line-data" data-line-start="227" data-line-end="228">If a dispute arises between you and Stock Knowledge, our goal is to provide you with a neutral and cost effective means of resolving the dispute quickly. Accordingly, you agree that we will resolve any claim or controversy at law or equity that relates to or arises out of the Terms of Use or the Services or your use of the Services (a “Claim“) in accordance with the subsections below.</p>
<p class="has-line-data" data-line-start="229" data-line-end="230">General. You and Stock Knowledge agree that any dispute, claim or controversy arising out of or relating to these Terms of Use or the breach, termination, enforcement, interpretation or validity thereof (collectively, “Disputes“) will be settled by binding arbitration, such as but not limited to the Philippine Dispute Resolution Center Inc, The ICC International Court of Arbitration, the Singapore International Arbitration Centre and the Hong Kong International Arbitration Centre; except that either party retains the right to bring an individual action in a court of competent jurisdiction. Without limiting the preceding sentence, you will also have the right to litigate any other Disputes if you provide Stock Knowledge with written notice of your desire to do so by email at <a href="mailto:legal@theknowledgetools.com"><span class="__cf_email__" data-cfemail="dfbcb0b1abbebcab9fabb7bab4b1b0a8b3babbb8baabb0b0b3acf1bcb0b2">legal@theknowledgetools.com</span></a> . Attn: General Counsel within thirty (30) days following the date you first agree to these Terms of Use (such notice, an “Arbitration Opt-out Notice”). If you do not provide Stock Knowledge with an Arbitration Opt-out Notice within the thirty (30) day period, you will be deemed to have knowingly and intentionally waived your right to litigate any Dispute except as expressly set forth with respect to individual actions a court of competent jurisdiction. You acknowledge and agree that you and Stock Knowledge are each waiving the right to a trial or to participate as a plaintiff or class member in any purported class action or representative proceeding. Further, unless both you and Stock Knowledge otherwise agree, the arbitrator may not consolidate more than one person’s claims, and may not otherwise preside over any form of any class or representative proceeding. If this specific paragraph is held unenforceable, then the entirety of this “Legal Disputes” section will be deemed void. This “Legal Disputes” section will survive any termination of these Terms of Use. Notwithstanding the foregoing, each party reserves the right to seek injunctive or other equitable relief in a court of competent jurisdiction with respect to any dispute related to the actual or threatened infringement, misappropriation or violation of a party’s intellectual property or proprietary rights or breach of the User Content and Activities provisions of this Agreement.</p>
<p class="has-line-data" data-line-start="233" data-line-end="234">Policies</p>
<p class="has-line-data" data-line-start="235" data-line-end="236">When using the Services, you are subject to any posted policies or rules applicable to features you use through the Services, including without limitation the General Policies and all policies referenced in the General Policies or elsewhere in this Agreement. All such policies or rules are hereby incorporated into these Terms of Use. These policies may change from time to time.</p>
<p class="has-line-data" data-line-start="237" data-line-end="238">Privacy Policy</p>
<p class="has-line-data" data-line-start="239" data-line-end="240">Please refer to our Privacy Policy (<a href="http://www.theknowledgetools.com/privacypolicy">www.theknowledgetools.com/privacypolicy</a>) for information on how we collect, use and disclose information from our users. You acknowledge and agree that your use of the Services is subject to our Privacy Policy</p>
<p class="has-line-data" data-line-start="241" data-line-end="242">List Prices</p>
<p class="has-line-data" data-line-start="243" data-line-end="244">The list prices displayed on the Services for publications come from bibliographic information we receive from leading third-party sources and publishers. Each list price is the publisher’s suggested retail price. To the fullest extent permitted under applicable law, Stock Knowledge is not responsible for errors in that third-party data, including prices for the sale or purchase (buyback) of books. If a title does not have a publisher’s suggested list price, the Services may not show a list price in the online catalog. If a product is listed at an incorrect price due to typographical error or an error in pricing information received from our suppliers or for any other reason, Stock Knowledge shall have the right to refuse or cancel any order (to the fullest extent permitted under applicable law), whether or not the order has been confirmed and your credit or debit card charged. If your credit or debit card has already been charged and your order is canceled, Stock Knowledge will issue a credit to your credit or debit card account.</p>
<p class="has-line-data" data-line-start="245" data-line-end="246">Stock Knowledge Credit</p>
<p class="has-line-data" data-line-start="247" data-line-end="248">From time to time, Stock Knowledge may issue you “Stock Knowledge Credit.” Upon providing you Stock Knowledge Credit, to the fullest extent permitted under applicable law, Stock Knowledge may place limits on its use, and Stock Knowledge Credit may not be moved from one Stock Knowledge Service to another. If provided to you in exchange for goods or services or as a refund, it will not expire, though we may with notice after a posted period of time convert your credit to cash and send it to your address of record. If the credit was given to you with terms explicitly authorizing redemption for cash, you may convert that credit to cash. If you receive a credit from customer support, you may not redeem it for cash.</p>
<p class="has-line-data" data-line-start="249" data-line-end="250">Stock Knowledge Discount Codes, Bonuses, Coupons, Loyalty Programs, Points Programs &amp; Other Promotions</p>
<p class="has-line-data" data-line-start="251" data-line-end="252">From time to time, Stock Knowledge may offer discounts, bonuses, coupons, loyalty programs, points programs, sweepstakes, contests or other promotional incentives. These incentives typically have their own specific rules, restrictions and limitations (e.g., limiting when, how often, and under what circumstances you may be eligible for the promotion). You are responsible for carefully reviewing and complying with these applicable rules, restrictions and limitations. You agree not to engage in any self-dealing, collusion, smurfing (defined as breaking large orders or sales transactions into multiple individual transactions for the purpose of obtaining multiple discounts or payments), or otherwise gaming or defrauding the system. By participating in such promotions, you agree to be bound by the applicable rules and restrictions, and that Stock Knowledge, in its sole discretion, may deny payment or benefits to the fullest extent permitted under applicable law (e.g., when it believes improper activity has occurred or when a code has expired). All promotions may expire at any time without notice to recipients. Discounts apply only toward the actual base product/service rental or purchase cost; they do not apply to taxes, shipping, extension or late fees, or any other additional fees (e.g., conversion to purchase fees).</p>
<p class="has-line-data" data-line-start="253" data-line-end="254">Return of Digital Access Codes</p>
<p class="has-line-data" data-line-start="255" data-line-end="256">Through the Services, you may purchase, as a separate product, a digital access code (DAC) to certain Digital Content. The DAC publishers allow only one user (one activation) of these codes. Stock Knowledge will ship your ordered DAC to you in sealed packaging. If the DAC packaging is opened, Stock Knowledge must assume that the code is activated and therefore cannot be resold. Thus, you may not return a DAC with opened packaging for a refund.</p>
<p class="has-line-data" data-line-start="257" data-line-end="258">Tax</p>
<p class="has-line-data" data-line-start="259" data-line-end="260">Rentals and purchases through the Services may be subject to taxes. In addition to the taxes required under Philippine laws, you may also be required to pay, taxes, fees, or charges by your state, depending on your tax laws and the nature of the product or service you receive from us. Tax rates are different from state to state. You are responsible for paying all such taxes.</p>
<p class="has-line-data" data-line-start="261" data-line-end="262">Supplemental Materials</p>
<p class="has-line-data" data-line-start="263" data-line-end="264">Unfortunately, we cannot guarantee that supplemental materials (CDs and CD-ROMs, Workbooks, Study Guides) will be included with book rentals. However, they are available for purchase on select titles. If you receive your rental book with any of the above items, you are welcome to use it. We ask that you return your book complete with any supplemental materials you received.</p>
<p class="has-line-data" data-line-start="265" data-line-end="266">Asset Ownership</p>
<p class="has-line-data" data-line-start="267" data-line-end="268">All rentals remain the property of Stock Knowledge even while the item is in your possession. You may be given the option to purchase rented books from Stock Knowledge, either at the end of a rental cycle or at any point during the rental cycle. If you wish to purchase a book you have rented through the Services, you may be able to do so by accessing your account on the Services and looking for the purchase option. In this case, title (ownership) transfers to you as soon as your credit or debit card is approved for purchase value. If you purchase the title through our purchase program, title (ownership) changes hands when we provide the book to the shipping company. Certain digital products may not be available for purchase or may have different purchase terms, and you should review their specific terms prior to rental or purchase.</p>
<p class="has-line-data" data-line-start="269" data-line-end="270">Certain Payments and Renewals</p>
<p class="has-line-data" data-line-start="271" data-line-end="272">Payment for certain Services is due in advance of each applicable membership period (e.g., monthly or annually). MONTHLY AND ANNUAL MEMBERSHIPS MAY AUTOMATICALLY RENEW AND YOUR CREDIT CARD OR OTHER PAYMENT METHOD YOU PROVIDE WILL BE CHARGED ON THE FIRST DAY OF EACH RENEWAL PERIOD UNTIL YOUR MEMBERSHIP IS TERMINATED BY US OR CANCELLED BY YOU. Also, for some of our paid Services, you may elect to temporarily “suspend” your membership, for example, during school breaks or vacation, for up to a total of 90 days in any one membership year (i.e., during each 12-month period following the commencement of your membership), and the period of your membership will be extended by the total amount of such suspended period(s). You agree to pay all applicable fees for your memberships and use of our paid Services, plus any applicable taxes or other charges as may be required, when due and payable. All fees and charges are payable in advance and non-refundable, including after cancellation, unless otherwise disclosed at the time of purchase. If you wish to cancel your membership in a Service (if available), please visit the customer support web area on the Services. Cancellation of memberships (if available) will take effect as detailed in the cancellation information for the specific Service you want to cancel.</p>
<p class="has-line-data" data-line-start="273" data-line-end="274">Free Trial Memberships</p>
<p class="has-line-data" data-line-start="275" data-line-end="276">We may from time to time offer free trials for some of our Services. Such trials may require you to register with a valid credit card to commence. Users that sign up for a free trial membership at a particular level will be automatically renewed at the promoted membership rate for that level at the end of the trial period unless the user cancels the membership at least before the end of the trial, unless the terms of the offer explicitly state otherwise. You can cancel a free trial online on the Services or by contacting Stock Knowledge’s customer support. After cancellation of a free trial, you may be able to continue as a Free Member with reduced benefits or access. Only one free trial membership is allowed per person. Subsequent registrations do not qualify for free trials. Unless the terms of a promotion state otherwise, for promotions that include “free” periods with “paid” periods, paid periods will elapse first. We may introduce new or additional features, services or materials to the Services which may be a part of, or priced separately from, existing levels of membership at our sole discretion.</p>
<p class="has-line-data" data-line-start="277" data-line-end="278">Stock Knowledge Honor Code</p>
<p class="has-line-data" data-line-start="279" data-line-end="280">We know that most of you have never and will never abuse the Services or any of the information, services or materials available through them. You agree to abide by our Honor Code.</p>
<p class="has-line-data" data-line-start="281" data-line-end="282">You may not use any of the solutions, answers, materials or information available on or through the Services, to cheat. Examples include:</p>
<p class="has-line-data" data-line-start="283" data-line-end="284">Submitting any textbook solutions from the Services as your own to any class.</p>
<ol start="2">
<li class="has-line-data" data-line-start="284" data-line-end="285">Using our questions and answers service to complete tests or homework when instructed not to use outside help.</li>
<li class="has-line-data" data-line-start="285" data-line-end="286">Otherwise passing along any solutions, answers, materials or information from the Services as your own.</li>
<li class="has-line-data" data-line-start="286" data-line-end="289">Any other violation of your instructor’s or school’s academic honor code.<br>
We will take swift action against anyone found violating this Honor Code. If Stock Knowledge is presented with evidence that its Services have been used in a manner contrary to its Honor Code or any other part of these Terms of Use, Stock Knowledge may, in its sole discretion, remove the materials and terminate the account of the involved users.</li>
</ol>
<p class="has-line-data" data-line-start="289" data-line-end="290">Miscellaneous</p>
<p class="has-line-data" data-line-start="291" data-line-end="292">Unless otherwise stated in these Terms of Use, if any provision of the Terms of Use is declared invalid, illegal or unenforceable, all remaining provisions continue in full force and effect. The failure of Stock Knowledge to exercise or enforce any right or provision of the Terms of Use is not a waiver of such right or provision. The section titles of the Terms of Use are for convenience only and have no legal or contractual effect. Non-performance of either party, except for the failure to make required payments, will be excused to the extent performance is delayed or rendered impossible by any reason where failure to perform is beyond the reasonable control of the non-performing party. This “Miscellaneous” section shall survive any expiration or termination of your relationship with Stock Knowledge.</p>
<p class="has-line-data" data-line-start="293" data-line-end="294">Changes</p>
<p class="has-line-data" data-line-start="295" data-line-end="296">Stock Knowledge may modify the Terms of Use including the linked policies contained herein from time to time (“Updated Terms”). You agree that we may notify you of the Updated Terms by posting them on the Stock Knowledge Website so that they are accessible via a link on the home page, and that your use of our Services after we have posted the Updated Terms (or engaging in such other conduct as we may reasonably specify), you agree to be bound by the then-current version of the Terms of Use, including any changes we may have made since the last time you used our Services. It is therefore important that you review the Terms of Use regularly to ensure you are aware of any such changes. The updated Terms of Use will be effective as of the time of posting, or such later date as may be specified in the updated Terms of Use, and will apply to your use of the Services from that point forward.</p>
<p class="has-line-data" data-line-start="297" data-line-end="298">Entire Agreement</p>
<p class="has-line-data" data-line-start="299" data-line-end="300">The then-current Terms of Use, including (a) any related policies and terms referenced in the Terms of Use and (b) any Additional Terms, are the entire agreement between you and Stock Knowledge regarding the Services. The Terms of Use may not be modified without the consent of a duly authorized representative of Stock Knowledge, and will supersede and prevail over any terms or conditions you may include with any purchase order or other transaction document or communication with us, regardless of whether Stock Knowledge signs them or fails to object to them. This “Entire Agreement” section shall survive any expiration or termination of your relationship with Stock Knowledge.</p>
<p class="has-line-data" data-line-start="301" data-line-end="302">Contacting Stock Knowledge</p>
<p class="has-line-data" data-line-start="303" data-line-end="304">If you have any questions or concerns regarding the Stock Knowledge Websites or Services, please write to us at <a href="https://www.theknowledgetools.com/contact-us/">https://www.theknowledgetools.com/contact-us/</a></p>


</div></div>
<?php include('../footer.php');?>

</body>
</html> 
